export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART';
export const PURCHASE = 'PURCHASE';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILURE = 'PURCHASE_FAILURE';
export const SHOW_PURCHASE_MODAL = 'SHOW_PURCHASE_MODAL';
export const HIDE_PURCHASE_MODAL = 'HIDE_PURCHASE_MODAL';
export const CLEAR_CART = 'CLEAR_CART';
