export const LOAD_ALL_BOOKS = 'LOAD_ALL_BOOKS';
export const LOAD_ALL_BOOKS_FAILURE = 'LOAD_ALL_BOOKS_FAILURE';
export const LOAD_ALL_BOOKS_SUCCESS = 'LOAD_ALL_BOOKS_SUCCESS';
export const LOAD_BOOK = 'LOAD_BOOK';
export const LOAD_BOOK_FAILURE = 'LOAD_BOOK_FAILURE';
export const LOAD_BOOK_SUCCESS = 'LOAD_BOOK_SUCCESS';
export const SET_BOOKS_SEARCH = 'SET_BOOKS_SEARCH';
export const SET_BOOKS_FILTER = 'SET_BOOKS_FILTER';
